management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka}
    instance:
      preferIpAddress: true